### ISSUE TITLE
flatpak-manager-client keeps failing with ValueError when building org.libreoffice.LibreOffice on flathub

### ISSUE THREAD

**Issue by stbergmann** [flatpak/flat-manager#8] opened 2019-03-14 09:36 UTC
Caused latest two build attempts <https://flathub.org/builds/#/builders/32/builds/770> and <https://flathub.org/builds/#/builders/32/builds/1098> to fail, see <https://flathub.org/builds/#/builders/32/builds/1098/steps/11/logs/stdio>:

```
Traceback (most recent call last):
  File "/srv/buildbot-master/sandbox/lib/python3.4/site-packages/buildbot/scripts/flat-manager-client", line 539, in <module>
    res = args.func(args)
  File "/srv/buildbot-master/sandbox/lib/python3.4/site-packages/buildbot/scripts/flat-manager-client", line 434, in commit_command
    commit_build(args.build_url, args.wait, args.token)
  File "/srv/buildbot-master/sandbox/lib/python3.4/site-packages/buildbot/scripts/flat-manager-client", line 291, in commit_build
    job = wait_for_job (job_url, token);
  File "/srv/buildbot-master/sandbox/lib/python3.4/site-packages/buildbot/scripts/flat-manager-client", line 241, in wait_for_job
    raise ApiError(resp, resp.json())
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tilosp** [comment] 2019-03-14 15:58
Duplicate of #2

**Closed** 2019-06-17 09:19 UTC
